parameters:
#    test.example.class: phpunit_symfony\testBundle\Example

services:
#    test.example:
#        class: %test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
